service: sqsemailsender
frameworkVersion: '1'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource:
        Fn::GetAtt: [ SQSQueue, Arn ]

functions:
  lambdaSendMessages:
    handler: sendMessages.producer
    environment:
      SQS_URL:
        Ref: SQSQueue
    events: 
      - schedule:
          rate: rate(1 minute)
  lambdaPoller:
    handler: poller.consumer
    events:
      - sqs:
          arn:
            Fn::GetAtt: [ SQSQueue, Arn ]

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: MySQSQueue
